version: '3.8'

services:
  feedback-widget:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    networks:
      - feedback-network

networks:
  feedback-network:
    driver: bridge